#!/usr/bin/perl

my $val=5;

print "prima della chiamata: $val\n";

testme() = 9;

print "dopo la chiamata: $val\n";

sub testme : lvalue
{
	$val = shift;
	print "dentro la subroutine: $val\n";
	print "valore ricevuto: ", $s, "\n";
	$val;
}
